CREATE TABLE users(
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT, 
    firstname VARCHAR(20) NOT NULL,
    lastname VARCHAR(20) NOT NULL,
    email VARCHAR(40) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    picture VARCHAR(50) NOT NULL DEFAULT 'user.jfif',
    regdate VARCHAR(20) NOT NULL,
    specialty VARCHAR(20) NOT NULL DEFAULT 'Not Specified',
    team_name VARCHAR(20) NOT NULL DEFAULT 'user_login',
    team_leader VARCHAR(2) NOT NULL DEFAULT '0',
    winner VARCHAR(2) NOT NULL DEFAULT '0'
);

CREATE TABLE admins(
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT, 
    firstname VARCHAR(20) NOT NULL,
    lastname VARCHAR(20) NOT NULL,
    email VARCHAR(40) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
);

CREATE TABLE notifications(
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT, 
    team_name VARCHAR(20) NOT NULL,
    team_leader VARCHAR(40) NOT NULL,
    user_email VARCHAR(40) NOT NULL
);

CREATE TABLE tasks(
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT, 
    description TEXT,
    start_date VARCHAR(15) NOT NULL,
    end_date VARCHAR(15) NOT NULL
);

CREATE TABLE teams(
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT, 
    team_name VARCHAR(10) NOT NULL,
    document VARCHAR(50) NOT NULL DEFAULT 'Nothing',
    disqualify VARCHAR(2) NOT NULL DEFAULT '0'
);

CREATE TABLE winners(
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT, 
    the_year VARCHAR(5) NOT NULL,
    start_month VARCHAR(2) NOT NULL,
    end_month VARCHAR(2) NOT NULL,
    team_name VARCHAR(10) NOT NULL,
    team_leader VARCHAR(40) NOT NULL,
    names TEXT NOT NULL
);