CREATE TABLE user_login(
    Id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT, 
    Firstname VARCHAR(20) NOT NULL,
    Lastname VARCHAR(20) NOT NULL,
    Email VARCHAR(40) NOT NULL UNIQUE,
    Password VARCHAR(100) NOT NULL,
    Picture VARCHAR(50) NOT NULL DEFAULT 'user.jfif',
    Regdate VARCHAR(20) NOT NULL,
    Specialty VARCHAR(20) NOT NULL DEFAULT 'Not Specified',
    Team_name VARCHAR(20) NOT NULL DEFAULT 'user_login',
    Tl VARCHAR(2) NOT NULL DEFAULT '0',
    Winner VARCHAR(2) NOT NULL DEFAULT '0'
);

CREATE TABLE admin_login(
    Id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT, 
    Firstname VARCHAR(20) NOT NULL,
    Lastname VARCHAR(20) NOT NULL,
    Email VARCHAR(40) NOT NULL UNIQUE,
    Password VARCHAR(100) NOT NULL,
);

CREATE TABLE notify(
    Id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT, 
    Team_name VARCHAR(20) NOT NULL,
    Team_leader VARCHAR(40) NOT NULL,
    User_email VARCHAR(40) NOT NULL
);

CREATE TABLE task(
    Id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT, 
    Description TEXT,
    Startdate VARCHAR(15) NOT NULL,
    Enddate VARCHAR(15) NOT NULL
);

CREATE TABLE teams(
    Id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT, 
    Team_name VARCHAR(10) NOT NULL,
    Document VARCHAR(50) NOT NULL DEFAULT 'Nothing',
    Disqualify VARCHAR(2) NOT NULL DEFAULT '0'
);

CREATE TABLE winners(
    Id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT, 
    The_year VARCHAR(5) NOT NULL,
    Start_month VARCHAR(2) NOT NULL,
    End_month VARCHAR(2) NOT NULL,
    Team_name VARCHAR(10) NOT NULL,
    Team_leader VARCHAR(40) NOT NULL,
    Names TEXT NOT NULL
);